### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by sscarduzio** [ntamas/react-flexible-workbench#16]
Hello, I was about to try to try use this code, but I see no license. It looks interesting, but can't really touch it at work if there's no license to it. And I think it's like this for many people stumbling upon this project.

So yeah, I would really appreciate if you add the license to this, and respect any decision you make about it.

**Comment by ntamas** [comment]
The package is MIT-licensed; I've added a separate `LICENSE.md` file to the `master` and `release/5.x` branches to clarify. `package.json` already contained a reference to the MIT license so no changes there, I'm just making things explicit.

On the other hand, note that this package is based on an ancient version of `golden-layout`; the authors of `golden-layout` have moved on with a new major version, but I did't have time to bring this package up-to-date or to provide proper documentation, so you'll have to rely on the examples to make things work in your project. `npm start` should spin up a Webpack dev server with a few examples.

If you need help with getting started, get in touch here and I'll see what I can do.

**Comment by sscarduzio** [comment]
Hi, and thanks for taking care of the license!

Yes I managed to run the examples successfully. Just later I realised the GoldenLayout dependency is very old and needs a refresh. But other than that, it does exactly what I need. Will try to spruce it up!

**Comment by ntamas** [comment]
The biggest hurdle is that React integration has been removed from `golden-layout` as far as I know, but actually I don't know whether there's something in the "new" `golden-layout` that you would need. We have been rolling with this version in [another project of mine](https://github.com/skybrush-io/live) for a long time and we are satisfied with the old version, so maybe you won't need an upgrade at all.

If you do decide to bring the codebase up-to-date with `golden-layout`'s more recent versions, I would be open to merging your modifications into this repo in the next major version.

**Comment by sscarduzio** [comment]
Man it looks much more complicated than I initially thought, I'm not even an expert React user. 

-- recap for who lands here from Google -- 

1. GoldenLayout can contain React components inside its windows 
2. **however** GoldenLayout cannot be (easily) contained in a React component
3. This repo contains a wrapper that makes it work, but it's an old version of GoldenLayout.
4. Not easy to port it to latest GL

As a result I'm giving a shot to https://github.com/caplin/FlexLayout which is a newer, React-first solution.
